"""
Single source of truth for deterministic rule-engine thresholds and weights.
Bump RULE_ENGINE_VERSION when any calibrated constant changes.
"""

from __future__ import annotations

RULE_ENGINE_VERSION = "1.0.0"

# Productivity formula weights
TASKS_COMPLETED_WEIGHT = 3.0
ATTENDANCE_DAYS_WEIGHT = 2.0
IDLE_HOURS_PENALTY = 1.0
PRODUCTIVITY_MIN = 0.0
PRODUCTIVITY_MAX = 100.0

# Telemetry ratio boost around target active ratio
ACTIVE_RATIO_TARGET = 0.55
ACTIVE_RATIO_SCALE = 40.0
ACTIVE_RATIO_CLAMP = 15.0
MIN_TELEMETRY_SECONDS_FOR_RATIO = 60
FRAGMENTATION_PENALTY_SCALE = 22.0
FRAGMENTATION_PENALTY_MAX = 12.0

# Burnout
BURNOUT_HIGH_HOURS = 10.0
BURNOUT_HIGH_HOURS_LOW_PROD = 9.0
BURNOUT_HIGH_PROD_THRESHOLD = 45.0
BURNOUT_IDLE_RATIO = 0.55
BURNOUT_IDLE_HOURS_MIN = 8.0
BURNOUT_MEDIUM_HOURS = 8.0
BURNOUT_MEDIUM_PROD = 55.0

# Task delay
DELAY_HIGH_PROGRESS = 50.0
DELAY_HIGH_DAYS_LEFT = 3
DELAY_MEDIUM_PROGRESS = 70.0

# Attendance pattern
LATE_IRREGULAR = 4
ABSENT_IRREGULAR = 3
LATE_MONITOR = 2
ABSENT_MONITOR = 1
FIRST_SEEN_LATE_60 = 60
FIRST_SEEN_LATE_120 = 120

# Benchmark z-scores
BENCHMARK_WARMUP_SAMPLES = 5
BENCHMARK_DECLINE_Z = -1.5
BENCHMARK_IMPROVE_Z = 1.5

# Anomaly
ANOMALY_EXCESSIVE_HOURS = 11.0
ANOMALY_IDLE_HOURS = 6.0
ANOMALY_IDLE_RATIO = 0.62
ANOMALY_PROD_DROP = 30.0
ANOMALY_OUTLIER_Z = -2.0

# Telemetry signal quality
SPARSE_WH_SEG_THRESHOLD = 4.0
SPARSE_MIN_SEGMENTS = 2
SPARSE_LOW_WH = 1.0

# Confidence priors
CONFIDENCE_BASE = 0.72
CONFIDENCE_SPARSE_PENALTY = 0.28
CONFIDENCE_HISTORY_BONUS_PER = 0.04
CONFIDENCE_HISTORY_BONUS_CAP = 0.2
CONFIDENCE_TELEMETRY_BONUS = 0.06
CONFIDENCE_MIN = 0.25
CONFIDENCE_MAX = 0.95

# Smart attendance recommendation thresholds
SMART_LOW_RELIABILITY = 55.0
SMART_IRREGULAR_RANK = 2
